#Data Analysis on a Credit Score

In [ ]:
# I imported all my necessary libraries and also the credit score classification dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import plotly

data = pd.read_csv('/content/Credit_Score_Classification.csv')
df = data.copy()
df

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x25fe9,CUS_0x942c,April,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,High_spent_Large_value_payments,479.866228,Poor
99996,0x25fea,CUS_0x942c,May,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,High_spent_Medium_value_payments,496.65161,Poor
99997,0x25feb,CUS_0x942c,June,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,High_spent_Large_value_payments,516.809083,Poor
99998,0x25fec,CUS_0x942c,July,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,Low_spent_Large_value_payments,319.164979,Standard
99999,0x25fed,CUS_0x942c,August,Nicks,25,078-73-5990,Mechanic,39628.99_,3359.415833,4,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,!@9#%8,393.673696,Poor

In [ ]:
# I checked for the first row of the dataset
df.head(1)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.82262,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good

In [ ]:
## I placed both the categorical data and numerical data in different places
categorical = df.select_dtypes(include = ['object', 'category'])
numerical = df.select_dtypes(include = 'number')
print(f'Categorical df')
display(categorical.head(2))
print(f'\n\nNumerical df')
display(numerical.head(2))

Categorical df

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Num_of_Loan,Type_of_Loan,Num_of_Delayed_Payment,Changed_Credit_Limit,Credit_Mix,Outstanding_Debt,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",7,11.27,_,809.98,22 Years and 1 Months,No,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",NaN,11.27,Good,809.98,NaN,No,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good

Numerical df

,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Delay_from_due_date,Num_Credit_Inquiries,Credit_Utilization_Ratio,Total_EMI_per_month
0,1824.843333,3,4,3,3,4.0,26.82262,49.574949
1,NaN,3,4,3,-1,4.0,31.94496,49.574949

In [ ]:
## I noticed that there was some error in the seperation of the categorical data from the numerical data
## I decided to clean the data set
# Age
df['Age'].sample(200).values
df.Age = df['Age'].str.replace('-', '')
df.Age = df['Age'].str.replace('_', '')
df.Age = df.Age.astype(int)
df.Age.dtypes

dtype('int64')

In [ ]:
# Annual_Income
df['Annual_Income'].sample(200).values
df.Annual_Income = df['Annual_Income'].str.replace('_', '')
df.Annual_Income = df.Annual_Income.astype(float)
df.Annual_Income.dtypes

dtype('float64')

In [ ]:
# Num_of_Loan
df['Num_of_Loan'].sample(200).values
df.Num_of_Loan = df['Num_of_Loan'].str.replace('-', '')
df.Num_of_Loan = df['Num_of_Loan'].str.replace('_', '')
df.Num_of_loan = df['Num_of_Loan'].astype(str).str.replace('.', '')
df.Num_of_Loan = df.Num_of_Loan.astype(float)
df.Num_of_Loan.dtypes

dtype('float64')

In [ ]:
# Num_of_Delayed_Payment
df['Num_of_Delayed_Payment'].sample(200).values
df.Num_of_Delayed_Payment = df['Num_of_Delayed_Payment'].str.replace('_', '')
df.Num_of_Delayed_Payment = df.Num_of_Delayed_Payment.astype(float)
df.Num_of_Delayed_Payment.dtypes

dtype('float64')

In [ ]:
# Changed_Credit_Limit
df['Changed_Credit_Limit'].sample(200).values
df.Changed_Credit_Limit = df['Changed_Credit_Limit'].str.replace('-', '')
df.Changed_Credit_Limit = df['Changed_Credit_Limit'].str.replace('_', '')
df.Changed_Credit_Limit = pd.to_numeric(df.Changed_Credit_Limit, errors = 'coerce')
df.Changed_Credit_Limit.dtypes

dtype('float64')

In [ ]:
# Outstanding_Debt
df['Outstanding_Debt'].sample(200).values
df.Outstanding_Debt = df['Outstanding_Debt'].str.replace('-', '')
df.Outstanding_Debt = df['Outstanding_Debt'].str.replace('_', '')
df.Outstanding_Debt = df.Outstanding_Debt.astype(float)
df.Outstanding_Debt.dtypes

dtype('float64')

In [ ]:
# Amount_invested_monthly
df['Amount_invested_monthly'].sample(200).values
df.Amount_invested_monthly = df['Amount_invested_monthly'].str.replace('-', '')
df.Amount_invested_monthly = df['Amount_invested_monthly'].str.replace('_', '')
df.Amount_invested_monthly = df.Amount_invested_monthly.astype(float)
df.Amount_invested_monthly.dtypes

dtype('float64')

In [ ]:
# Monthly_Balance
df['Monthly_Balance'].sample(200).values
df.Monthly_Balance = df['Monthly_Balance'].str.replace('-', '')
df.Monthly_Balance = df['Monthly_Balance'].str.replace('_', '')
df.Monthly_Balance = df.Monthly_Balance.astype(float)
df.Monthly_Balance.dtypes

dtype('float64')

In [ ]:
## I confirmed here if my categorical and numerical data are well arranged
categorical = df.select_dtypes(include = ['object', 'category'])
numerical = df.select_dtypes(include = 'number')
print(f'Categorical df')
display(categorical.head(2))
print(f'\n\nNumerical df')
display(numerical.head(2))

Categorical df

,ID,Customer_ID,Month,Name,SSN,Occupation,Type_of_Loan,Credit_Mix,Credit_History_Age,Payment_of_Min_Amount,Payment_Behaviour,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,821-00-0265,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",_,22 Years and 1 Months,No,High_spent_Small_value_payments,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,821-00-0265,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,NaN,No,Low_spent_Large_value_payments,Good

Numerical df

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance
0,23,19114.12,1824.843333,3,4,3,4.0,3,7.0,11.27,4.0,809.98,26.82262,49.574949,80.415295,312.494089
1,23,19114.12,NaN,3,4,3,4.0,-1,NaN,11.27,4.0,809.98,31.94496,49.574949,118.280222,284.629162

In [ ]:
# I worked on the columns that has null values
for i in df.columns:
  if((df[i].isnull().sum()/ len(df)) * 100) > 30:
    df.drop([i], axis = 1, inplace = True)

  elif df[i].dtypes == 'O':
    df[i].fillna(df[i].mode()[0], inplace = True)

  else:
    df[i].fillna(df[i].median(), inplace = True)

df.isnull().sum()

ID                          0
Customer_ID                 0
Month                       0
Name                        0
Age                         0
SSN                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Type_of_Loan                0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

In [ ]:
# I checked to verify
df.isnull().sum()

ID                          0
Customer_ID                 0
Month                       0
Name                        0
Age                         0
SSN                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Type_of_Loan                0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

In [ ]:
df.describe()

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance
count,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05
mean,119.509700,1.764157e+05,4029.084964,17.091280,22.47443,72.466040,10.761960,21.068780,29.738370,10.443395,27.326780,1426.220376,32.285173,1403.118217,614.951381,3.000000e+22
std,684.757313,1.429618e+06,2961.363540,117.404834,129.05741,466.422621,61.789933,14.860104,218.017612,6.602381,191.293766,1155.129026,5.116875,8306.041270,1999.726647,3.162151e+24
min,14.000000,7.005930e+03,303.645417,-1.000000,0.00000,1.000000,0.000000,-5.000000,-3.000000,0.000000,0.000000,0.230000,20.000000,0.000000,0.000000,7.759665e-03
25%,25.000000,1.945750e+04,1792.084167,3.000000,4.00000,8.000000,2.000000,10.000000,9.000000,5.430000,3.000000,566.072500,28.052567,30.306660,77.017414,2.718395e+02
50%,34.000000,3.757861e+04,3093.745000,6.000000,5.00000,13.000000,3.000000,18.000000,14.000000,9.400000,6.000000,1166.155000,32.305784,69.249473,135.925682,3.364770e+02
75%,42.000000,7.279092e+04,5371.525000,7.000000,7.00000,20.000000,6.000000,28.000000,18.000000,14.660000,9.000000,1945.962500,36.496663,161.224249,255.038698,4.635469e+02
max,8698.000000,2.419806e+07,15204.633333,1798.000000,1499.00000,5797.000000,1496.000000,67.000000,4397.000000,36.970000,2597.000000,4998.070000,50.000000,82331.000000,10000.000000,3.333333e+26

In [ ]:
## I checked for outliners
def outlierRemoval(dataframe):
  for i in dataframe.columns:
    if dataframe[i].dtypes != 'O':
      Q1 = dataframe[i].describe()[4]
      Q3 = dataframe[i].describe()[6]
      IQR = Q3 - Q1
      minThreshold = Q1 - 1.5 * IQR
      maxThreshold = Q3 + 1.5 * IQR

      dataframe = dataframe.loc[(dataframe[i] >= minThreshold) & (dataframe[i] <= maxThreshold)]
  return dataframe

In [ ]:
df = outlierRemoval(df)
df

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.415295,High_spent_Small_value_payments,312.494089,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,3093.745000,3,...,Good,809.98,31.944960,15 Years and 11 Months,No,49.574949,118.280222,Low_spent_Large_value_payments,284.629162,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,3093.745000,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.458074,Low_spent_Small_value_payments,223.451310,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153,High_spent_Medium_value_payments,341.489231,Good
5,0x1607,CUS_0xd40,June,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,3093.745000,3,...,Good,809.98,27.262259,22 Years and 6 Months,No,49.574949,62.430172,!@9#%8,340.479212,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,0x25fe8,CUS_0x942c,March,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,39.323569,31 Years and 5 Months,No,35.104023,140.581403,High_spent_Medium_value_payments,336.477003,Poor
99995,0x25fe9,CUS_0x942c,April,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.971333,High_spent_Large_value_payments,336.477003,Poor
99996,0x25fea,CUS_0x942c,May,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.185950,High_spent_Medium_value_payments,336.477003,Poor
99998,0x25fec,CUS_0x942c,July,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.672582,Low_spent_Large_value_payments,336.477003,Standard
99999,0x25fed,CUS_0x942c,August,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.163865,!@9#%8,336.477003,Poor

DATA INSIGHTS

In [ ]:
# - What is the occupation of the customer name with the highest Annual Income
answer = df[['Occupation', 'Name', 'Annual_Income']]
answer.groupby(["Name", 'Occupation'])[['Annual_Income']].sum().sort_values(by = 'Annual_Income', ascending = False)

                            Annual_Income
Name          Occupation
Langep        _______        1.536852e+07
              Lawyer         1.445763e+07
              Entrepreneur   1.445678e+07
              Architect      1.372676e+07
              Mechanic       1.310512e+07
...                                   ...
Joshuaw       _______        7.136905e+03
Ering         _______        7.056405e+03
Martonc       _______        7.023160e+03
Ronaldh       _______        7.020545e+03
Scott Maloneu _______        7.019435e+03

[12732 rows x 1 columns]

In [ ]:
# - what month makes the most annual income
needed = df[['Month', 'Annual_Income']]
needed.groupby('Month')[['Annual_Income']].sum().sort_values(by = 'Annual_Income', ascending = False)

          Annual_Income
Month
February   2.637906e+08
January    2.605708e+08
March      2.591338e+08
April      2.564357e+08
June       2.559112e+08
May        2.554950e+08
July       2.539824e+08
August     2.506213e+08

In [ ]:
# - What Occupation has the most annual income
answer = df[['Occupation', 'Annual_Income']]
answer.groupby('Occupation')[['Annual_Income']].sum().sort_values(by = 'Annual_Income', ascending = False)

               Annual_Income
Occupation
_______         1.447514e+08
Lawyer          1.368823e+08
Scientist       1.343031e+08
Architect       1.318225e+08
Engineer        1.309500e+08
Mechanic        1.307457e+08
Entrepreneur    1.304473e+08
Writer          1.280137e+08
Accountant      1.267448e+08
Doctor          1.257492e+08
Developer       1.254803e+08
Journalist      1.247698e+08
Teacher         1.246681e+08
Media_Manager   1.244132e+08
Manager         1.187067e+08
Musician        1.174925e+08

In [ ]:
# - What Occupation has the most annual income
answer = df[['Occupation', 'Annual_Income']]
answer.groupby('Occupation')[['Annual_Income']].sum().sort_values(by = 'Annual_Income', ascending = False)

               Annual_Income
Occupation
_______         1.447514e+08
Lawyer          1.368823e+08
Scientist       1.343031e+08
Architect       1.318225e+08
Engineer        1.309500e+08
Mechanic        1.307457e+08
Entrepreneur    1.304473e+08
Writer          1.280137e+08
Accountant      1.267448e+08
Doctor          1.257492e+08
Developer       1.254803e+08
Journalist      1.247698e+08
Teacher         1.246681e+08
Media_Manager   1.244132e+08
Manager         1.187067e+08
Musician        1.174925e+08

In [ ]:
# - what occupation has the highest number of credit card
answer = df[['Occupation', 'Num_Credit_Card']]
top1 = answer.groupby('Occupation')[['Num_Credit_Card']].sum().sort_values(by = 'Num_Credit_Card', ascending = False)
top1.tail(3)

            Num_Credit_Card
Occupation
Doctor                18692
Manager               17373
Musician              17281

In [ ]:
# - What occupation has the least changed credit limit
answer = df[['Occupation', 'Changed_Credit_Limit']]
top1 = answer.groupby('Occupation')[['Changed_Credit_Limit']].sum().sort_values(by = 'Changed_Credit_Limit', ascending = True)
top1.head(1)

            Changed_Credit_Limit
Occupation
Musician                31528.42

In [ ]:
# - What occupation has the most outstanding debt
answer = df[['Occupation', 'Outstanding_Debt']]
answer.groupby('Occupation')[['Outstanding_Debt']].sum().sort_values(by = 'Outstanding_Debt', ascending = False)

               Outstanding_Debt
Occupation
_______              5010170.39
Engineer             4639515.68
Lawyer               4632898.55
Journalist           4625310.28
Mechanic             4574930.46
Developer            4539856.69
Scientist            4523543.93
Writer               4522156.00
Accountant           4512995.82
Doctor               4461980.38
Teacher              4338528.55
Entrepreneur         4326274.32
Architect            4286883.61
Media_Manager        4267090.78
Manager              4219652.75
Musician             3796944.80